##Docker file for runner that deploys ARC from rpms on rocky 9

FROM rockylinux:9
MAINTAINER Maiken Pedersen <maiken.pedersen@usit.uio.no> 

ENV OS_V=9
ENV OS=rocky

ENV arcnightly=2025-01-22
ENV basearch=x86_64

RUN dnf install -y epel-release

RUN dnf install -y 'dnf-command(config-manager)'
RUN dnf config-manager --set-enabled crb


RUN echo -e  '\
[nordugrid-nightly] \n\
name=Nordugrid ARC Next Nightly Builds - \$basearch \n\
baseurl=http://builds.nordugrid.org/nightlies/nordugrid-arc/next/2025-01-22/rocky/9/x86_64 \n\
enabled=1 \n\
gpgcheck=0 \n\
' >  /etc/yum.repos.d/nordugrid-nightly.repo 


EXPOSE 443
COPY ./entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]



